kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: todo-demo-app
spec:
  to:
    kind: Service
    name:  {{ include "todo-demo-app.fullname" . }}
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
