apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: todo-demo-app-git
  labels:
    app: todo-demo-app
  namespace: todo-demo-app
spec:
  type: git
  params:
  - name: url
    value: https://github.com/tosin2013/todo-demo-app.git
  - name: revision
    value: main
