apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-demo-app-helm-workspace-pvc
  namespace: todo-demo-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
