apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: push-todo-demo-app-image-to-quay
  namespace: todo-demo-app
spec:
  params:
    - default: quay.io/takinosh/todo-demo-app
      description: The quay.io repository in which to store the image.
      name: quay-io-repository
      type: string
    - default: latest
      description: The tag to use to identify the image.
      name: quay-io-image-tag-name
      type: string
    - default: overlay
      description: The Buildah storage driver.
      name: STORAGE_DRIVER
      type: string
  steps:
    - computeResources: {}
      image: registry.redhat.io/rhel9/podman
      name: podman-pull-image
      script: |
        #!/bin/sh
        podman pull --tls-verify=false \
          docker://image-registry.openshift-image-registry.svc:5000/todo-demo-app/todo-demo-app-image:$(params.quay-io-image-tag-name)
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/containers
          name: varlibcontainers
    - computeResources: {}
      image: registry.redhat.io/rhel9/buildah
      name: buildah-tag-image
      script: |
        #!/bin/sh
        buildah --storage-driver=$(params.STORAGE_DRIVER) tag \
          image-registry.openshift-image-registry.svc:5000/todo-demo-app/todo-demo-app-image:$(params.quay-io-image-tag-name) \
          $(params.quay-io-repository):$(params.quay-io-image-tag-name)
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/containers
          name: varlibcontainers
    - computeResources: {}
      image: registry.redhat.io/rhel9/buildah
      name: buildah-list-images-after-tagging
      script: |
        #!/bin/sh
        buildah --storage-driver=$(params.STORAGE_DRIVER) images
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/containers
          name: varlibcontainers
    - computeResources: {}
      image: registry.redhat.io/rhel9/buildah
      name: push-todo-demo-app-image-to-quay
      script: |
        #!/bin/sh
        ls -lath /etc/secret-volume/.dockerconfigjson 
        buildah --storage-driver=$(params.STORAGE_DRIVER) push --tls-verify=false \
          --authfile /etc/secret-volume/.dockerconfigjson \
          $(params.quay-io-repository):$(params.quay-io-image-tag-name)
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /etc/secret-volume
          name: secret-volume
          readOnly: true
        - mountPath: /var/lib/containers
          name: varlibcontainers
  volumes:
    - emptyDir: {}
      name: varlibcontainers
    - name: secret-volume
      secret:
        secretName: container-registry-secret
  workspaces:
    - description: Workspace for shared storage
      name: helm-shared-workspace
