apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  creationTimestamp: '2024-11-19T13:30:44Z'
  generation: 1
  managedFields:
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:params': {}
          'f:steps': {}
          'f:workspaces': {}
      manager: Mozilla
      operation: Update
      time: '2024-11-19T13:30:44Z'
  name: update-image-tag-in-git
  namespace: default
  resourceVersion: '2999395'
  uid: da03013f-e8f4-4e7b-8225-19a29a16567b
spec:
  params:
    - description: Git repository containing manifest files to update
      name: GIT_REPOSITORY
      type: string
    - default: pipeline@example.com
      description: Email address for Git commits
      name: GIT_EMAIL
      type: string
    - default: todo-demo-app
      description: Name for Git commits
      name: GIT_NAME
      type: string
    - default: yamls/ocp
      description: Directory in the repository containing manifest files
      name: GIT_MANIFEST_DIR
      type: string
    - default: quay.io/takinosh/todo-demo-app
      description: Target registry name
      name: TARGET_IMAGE
      type: string
    - default: v1
      description: Target image tag
      name: TARGET_TAG
      type: string
    - default: '1'
      description: Number of replicas
      name: REPLICA_COUNT
      type: string
    - description: Username for Git authentication
      name: GIT_USERNAME
      type: string
    - description: Token or password for Git authentication
      name: GIT_TOKEN
      type: string
  steps:
    - image: 'quay.io/takinosh/tekton-tools:latest'
      name: update-manifest
      resources: {}
      script: |
        #!/bin/bash
        set -eu

        # Configure Git
        git config --global user.email "$(params.GIT_EMAIL)"
        git config --global user.name "$(params.GIT_NAME)"

        # Clone the repository
        git clone --branch main --depth 1 https://$(params.GIT_USERNAME):$(params.GIT_TOKEN)@$(params.GIT_REPOSITORY) /workspace/source/repo
        cd /workspace/source/repo/$(params.GIT_MANIFEST_DIR)

        # Display current values
        echo "Current image repository: $(yq e '.image.repository' app/values.yaml)"
        echo "Current image tag: $(yq e '.image.tag' app/values.yaml)"
        echo "Current replica count: $(yq e '.replicaCount' app/values.yaml)"

        # Update values
        yq e -i '.image.repository = "$(params.TARGET_IMAGE)"' app/values.yaml
        yq e -i '.image.tag = "$(params.TARGET_TAG)"' app/values.yaml
        yq e -i '.replicaCount = "$(params.REPLICA_COUNT)"' app/values.yaml

        # Verify changes
        echo "Updated values:"
        cat app/values.yaml

        # Commit and push changes if any
        if ! git diff-index --quiet HEAD --; then
          git add .
          git commit -m "Deployment updated by Tekton pipeline"
          git push https://$(params.GIT_USERNAME):$(params.GIT_TOKEN)@$(params.GIT_REPOSITORY) main
        else
          echo "No changes detected; repository is up to date."
        fi
      volumeMounts:
        - mountPath: /workspace/source
          name: source-workspace
  workspaces:
    - description: Workspace containing the cloned Git repository
      name: source-workspace
